/**
 * Cloud-Native Library Management System (LMS)
 * Production Database Seeder
 * Automatically populates MongoDB Atlas on boot if collections are empty.
 */

import bcrypt from 'bcrypt';
import { BookModel } from '../models/book.model';
import { UserModel } from '../models/user.model';
import { UserRole, UserStatus } from '../types/user.types';
import { BookGenre } from '../types/book.types';
import { logger } from '../utils/logger';

export async function seedDatabaseIfEmpty(): Promise<void> {
  try {
    const bookCount = await BookModel.countDocuments();
    if (bookCount === 0) {
      logger.info({ message: 'Catalog is empty. Seeding 24 default heritage & CS books...' });

      const SEED_BOOKS = [
        {
          title: 'Aryabhatiya & Classical Indian Mathematics',
          author: 'Aryabhata (Trans. Prof. K.S. Shukla)',
          isbn: '9788172360214',
          genre: BookGenre.SCIENCE,
          description: 'Foundational 5th-century treatise on trigonometry, algebra, quadratic equations, and astronomical computations.',
          publisher: 'Indian National Science Academy (INSA)',
          publicationYear: 1976,
          totalCopies: 5,
          availableCopies: 4,
          location: { aisle: 'Heritage Wing A1', shelf: 'Indic-04' },
          isDeleted: false,
        },
        {
          title: 'The Arthashastra: Science of Wealth & Statecraft',
          author: 'Kautilya (Chanakya)',
          isbn: '9780140446036',
          genre: BookGenre.PHILOSOPHY,
          description: 'Masterwork on statecraft, economic policy, institutional governance, and administrative intelligence in ancient India.',
          publisher: 'Penguin Classics India',
          publicationYear: 1992,
          totalCopies: 6,
          availableCopies: 6,
          location: { aisle: 'Heritage Wing B2', shelf: 'Indic-12' },
          isDeleted: false,
        },
        {
          title: 'The Discovery of India',
          author: 'Jawaharlal Nehru',
          isbn: '9780195623598',
          genre: BookGenre.HISTORY,
          description: 'Comprehensive exploration of Indian history, art, philosophy, and cultural evolution from the Indus Valley Civilization to independence.',
          publisher: 'Oxford University Press India',
          publicationYear: 1989,
          totalCopies: 5,
          availableCopies: 4,
          location: { aisle: 'Central Hall C1', shelf: 'History-02' },
          isDeleted: false,
        },
        {
          title: 'Concepts of Physics (Volume 1 & 2)',
          author: 'Dr. H.C. Verma',
          isbn: '9788177091878',
          genre: BookGenre.SCIENCE,
          description: 'Legendary Indian textbook presenting deep conceptual physics, mechanics, thermodynamics, and quantum fundamentals with unmatched clarity.',
          publisher: 'Bharati Bhawan',
          publicationYear: 2022,
          totalCopies: 8,
          availableCopies: 7,
          location: { aisle: 'STEM Wing D3', shelf: 'Physics-01' },
          isDeleted: false,
        },
        {
          title: 'Sanskrit Computational Linguistics: Paninian Grammar & NLP',
          author: 'Dr. Girish Nath Jha',
          isbn: '9783642175275',
          genre: BookGenre.COMPUTER_SCIENCE,
          description: 'Analysis of Paninis Ashtadhyayi formal grammar generative rules and their direct application in modern compiler theory and Natural Language Processing.',
          publisher: 'Springer',
          publicationYear: 2010,
          totalCopies: 4,
          availableCopies: 4,
          location: { aisle: 'Digital Wing E2', shelf: 'CS-09' },
          isDeleted: false,
        },
        {
          title: 'Designing Data-Intensive Applications',
          author: 'Martin Kleppmann',
          isbn: '9781449373320',
          genre: BookGenre.TECHNOLOGY,
          description: 'The big ideas behind reliable, scalable, and maintainable systems.',
          publisher: "O'Reilly Media",
          publicationYear: 2017,
          totalCopies: 5,
          availableCopies: 4,
          location: { aisle: 'Computing Wing A3', shelf: 'S2' },
          isDeleted: false,
        },
        {
          title: 'Clean Architecture: A Craftsman Guide',
          author: 'Robert C. Martin',
          isbn: '9780134494166',
          genre: BookGenre.TECHNOLOGY,
          description: 'A Craftsman Guide to Software Structure and Design.',
          publisher: 'Prentice Hall',
          publicationYear: 2017,
          totalCopies: 4,
          availableCopies: 4,
          location: { aisle: 'Computing Wing B1', shelf: 'S4' },
          isDeleted: false,
        },
        {
          title: 'Introduction to Algorithms (CLRS)',
          author: 'Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest',
          isbn: '9780262033848',
          genre: BookGenre.COMPUTER_SCIENCE,
          description: 'Comprehensive textbook on algorithms, data structures, dynamic programming, and computational complexity.',
          publisher: 'MIT Press',
          publicationYear: 2009,
          totalCopies: 6,
          availableCopies: 5,
          location: { aisle: 'Computing Wing A2', shelf: 'CS-01' },
          isDeleted: false,
        },
        {
          title: 'Wings of Fire: An Autobiography',
          author: 'Dr. A.P.J. Abdul Kalam & Arun Tiwari',
          isbn: '9788173711466',
          genre: BookGenre.BIOGRAPHY,
          description: 'Inspiring life journey of the Missile Man and former President of India, detailing perseverance and scientific leadership.',
          publisher: 'Universities Press India',
          publicationYear: 1999,
          totalCopies: 6,
          availableCopies: 5,
          location: { aisle: 'Biographies Wing C3', shelf: 'Bio-05' },
          isDeleted: false,
        },
        {
          title: 'The Upanishads: Classic of Indian Spirituality',
          author: 'Eknath Easwaran',
          isbn: '9781586380212',
          genre: BookGenre.PHILOSOPHY,
          description: 'Revered spiritual and philosophical discourses exploring the nature of consciousness, reality, and Self.',
          publisher: 'Nilgiri Press',
          publicationYear: 2007,
          totalCopies: 5,
          availableCopies: 5,
          location: { aisle: 'Heritage Wing B3', shelf: 'Indic-20' },
          isDeleted: false,
        },
        {
          title: 'India After Gandhi: The History of the Worlds Largest Democracy',
          author: 'Ramachandra Guha',
          isbn: '9780330505543',
          genre: BookGenre.HISTORY,
          description: 'Magisterial account of India post-1947, examining democratic endurance, social movements, and national unity.',
          publisher: 'Picador India',
          publicationYear: 2008,
          totalCopies: 5,
          availableCopies: 4,
          location: { aisle: 'Central Hall C2', shelf: 'History-08' },
          isDeleted: false,
        },
        {
          title: 'Panchatantra: Ancient Wisdom & Moral Statecraft',
          author: 'Pandit Vishnu Sharma',
          isbn: '9788171670659',
          genre: BookGenre.FICTION,
          description: 'Timeless interconnected animal fables illustrating practical wisdom, friendship, strategic alliance, and ethics.',
          publisher: 'Rupa Publications',
          publicationYear: 1993,
          totalCopies: 5,
          availableCopies: 5,
          location: { aisle: 'Heritage Wing A3', shelf: 'Fable-01' },
          isDeleted: false,
        },
        {
          title: 'Site Reliability Engineering',
          author: 'Betsy Beyer, Chris Jones, Jennifer Petoff',
          isbn: '9781491929124',
          genre: BookGenre.TECHNOLOGY,
          description: 'How Google Runs Production Systems with resilience, SLOs, error budgets, and distributed automation.',
          publisher: "O'Reilly Media",
          publicationYear: 2016,
          totalCopies: 4,
          availableCopies: 4,
          location: { aisle: 'Computing Wing C2', shelf: 'S1' },
          isDeleted: false,
        },
        {
          title: 'Building Microservices: Designing Fine-Grained Systems',
          author: 'Sam Newman',
          isbn: '9781492034025',
          genre: BookGenre.TECHNOLOGY,
          description: 'Distributed architecture principles and practical microservice design across cloud boundaries.',
          publisher: "O'Reilly Media",
          publicationYear: 2021,
          totalCopies: 5,
          availableCopies: 5,
          location: { aisle: 'Computing Wing B2', shelf: 'S3' },
          isDeleted: false,
        },
        {
          title: 'Database Internals: A Deep Dive',
          author: 'Alex Petrov',
          isbn: '9781492040347',
          genre: BookGenre.TECHNOLOGY,
          description: 'A deep dive into how distributed data storage engines, B-trees, LSM trees, and consensus protocols operate.',
          publisher: "O'Reilly Media",
          publicationYear: 2019,
          totalCopies: 4,
          availableCopies: 4,
          location: { aisle: 'Computing Wing A1', shelf: 'S1' },
          isDeleted: false,
        },
        {
          title: 'Operating System Concepts (Silberschatz)',
          author: 'Abraham Silberschatz, Peter B. Galvin, Greg Gagne',
          isbn: '9781119456339',
          genre: BookGenre.COMPUTER_SCIENCE,
          description: 'Core principles of concurrency, virtual memory, scheduling, process synchronization, and file systems.',
          publisher: 'Wiley',
          publicationYear: 2018,
          totalCopies: 5,
          availableCopies: 4,
          location: { aisle: 'Computing Wing B3', shelf: 'OS-02' },
          isDeleted: false,
        },
        {
          title: 'Gitanjali (Song Offerings)',
          author: 'Rabindranath Tagore',
          isbn: '9780143417095',
          genre: BookGenre.FICTION,
          description: 'Nobel Prize-winning collection of poetic devotion, philosophical reflection, and the beauty of human communion.',
          publisher: 'Penguin Classics',
          publicationYear: 2011,
          totalCopies: 5,
          availableCopies: 5,
          location: { aisle: 'Literature Wing D1', shelf: 'Poetry-03' },
          isDeleted: false,
        },
        {
          title: 'The Argumentative Indian: Writings on Indian History & Culture',
          author: 'Amartya Sen',
          isbn: '9780141012117',
          genre: BookGenre.PHILOSOPHY,
          description: 'Essays by the Nobel Laureate exploring Indias long tradition of public debate, intellectual skepticism, and pluralism.',
          publisher: 'Penguin Books',
          publicationYear: 2005,
          totalCopies: 5,
          availableCopies: 5,
          location: { aisle: 'Heritage Wing B1', shelf: 'Econ-04' },
          isDeleted: false,
        },
        {
          title: 'Structure and Interpretation of Computer Programs (SICP)',
          author: 'Harold Abelson & Gerald Jay Sussman',
          isbn: '9780262510875',
          genre: BookGenre.COMPUTER_SCIENCE,
          description: 'Landmark MIT curriculum on procedural abstraction, data modeling, metacircular evaluation, and functional paradigms.',
          publisher: 'MIT Press',
          publicationYear: 1996,
          totalCopies: 5,
          availableCopies: 4,
          location: { aisle: 'Computing Wing A4', shelf: 'CS-15' },
          isDeleted: false,
        },
        {
          title: 'A Brief History of Time',
          author: 'Stephen Hawking',
          isbn: '9780553380163',
          genre: BookGenre.SCIENCE,
          description: 'From the Big Bang to Black Holes: a masterpiece introducing cosmology, spacetime curvature, and quantum gravity.',
          publisher: 'Bantam Books',
          publicationYear: 1998,
          totalCopies: 6,
          availableCopies: 5,
          location: { aisle: 'STEM Wing D1', shelf: 'Astro-02' },
          isDeleted: false,
        },
        {
          title: 'Compilers: Principles, Techniques, and Tools (Dragon Book)',
          author: 'Alfred V. Aho, Monica S. Lam, Ravi Sethi, Jeffrey D. Ullman',
          isbn: '9780321486813',
          genre: BookGenre.COMPUTER_SCIENCE,
          description: 'The authoritative reference on lexical analysis, parsing, syntax-directed translation, and code optimization.',
          publisher: 'Pearson',
          publicationYear: 2006,
          totalCopies: 4,
          availableCopies: 4,
          location: { aisle: 'Computing Wing B4', shelf: 'CS-08' },
          isDeleted: false,
        },
        {
          title: 'Computer Networks: A Systems Approach',
          author: 'Larry L. Peterson & Bruce S. Davie',
          isbn: '9780123850591',
          genre: BookGenre.TECHNOLOGY,
          description: 'Comprehensive systems-oriented study of internet protocols, routing, congestion control, and modern transport architectures.',
          publisher: 'Morgan Kaufmann',
          publicationYear: 2011,
          totalCopies: 5,
          availableCopies: 5,
          location: { aisle: 'Computing Wing C3', shelf: 'Net-01' },
          isDeleted: false,
        },
        {
          title: 'Artificial Intelligence: A Modern Approach',
          author: 'Stuart Russell & Peter Norvig',
          isbn: '9780136042594',
          genre: BookGenre.COMPUTER_SCIENCE,
          description: 'The standard worldwide AI textbook on intelligent agents, probabilistic reasoning, reinforcement learning, and neural nets.',
          publisher: 'Prentice Hall',
          publicationYear: 2020,
          totalCopies: 5,
          availableCopies: 4,
          location: { aisle: 'Computing Wing A5', shelf: 'AI-01' },
          isDeleted: false,
        },
        {
          title: 'Refactoring: Improving the Design of Existing Code',
          author: 'Martin Fowler',
          isbn: '9780134757599',
          genre: BookGenre.SOFTWARE_ENGINEERING,
          description: 'Essential guide to identifying code smells and iteratively restructuring codebases with tests and confidence.',
          publisher: 'Addison-Wesley',
          publicationYear: 2018,
          totalCopies: 4,
          availableCopies: 4,
          location: { aisle: 'Computing Wing B5', shelf: 'SE-03' },
          isDeleted: false,
        },
      ];

      await BookModel.insertMany(SEED_BOOKS);
      logger.info({ message: '✅ Successfully seeded 24 catalog books into MongoDB!' });
    }

    const userCount = await UserModel.countDocuments();
    if (userCount === 0) {
      logger.info({ message: 'User database is empty. Seeding initial admin and patron accounts...' });

      const adminPassHash = await bcrypt.hash('AdminSecret123!', 12);
      const patronPassHash = await bcrypt.hash('PatronPassword123!', 12);

      const SEED_USERS = [
        {
          firstName: 'Yash',
          lastName: 'Singh',
          email: 'singhyash0706@gmail.com',
          passwordHash: adminPassHash,
          role: UserRole.ADMIN,
          status: UserStatus.ACTIVE,
          activeBorrowCount: 0,
          phoneNumber: '+919876543210',
        },
        {
          firstName: 'System',
          lastName: 'Admin',
          email: 'admin@lms.local',
          passwordHash: adminPassHash,
          role: UserRole.ADMIN,
          status: UserStatus.ACTIVE,
          activeBorrowCount: 0,
          phoneNumber: null,
        },
        {
          firstName: 'Arjun',
          lastName: 'Sharma',
          email: 'arjun.sharma@iitd.ac.in',
          passwordHash: patronPassHash,
          role: UserRole.PATRON,
          status: UserStatus.ACTIVE,
          activeBorrowCount: 0,
          phoneNumber: '+919876543210',
        },
        {
          firstName: 'Alex',
          lastName: 'Patron',
          email: 'patron@lms.local',
          passwordHash: patronPassHash,
          role: UserRole.PATRON,
          status: UserStatus.ACTIVE,
          activeBorrowCount: 0,
          phoneNumber: null,
        },
      ];

      await UserModel.insertMany(SEED_USERS);
      logger.info({ message: '✅ Successfully seeded initial users into MongoDB!' });
    }
  } catch (err: unknown) {
    logger.error({
      message: 'Failed to complete database seeding check',
      error: err instanceof Error ? err.message : String(err),
    });
  }
}
